- hosts: servers
  become: true
  user: {{ user }}
  gather_facts: false

  tasks:

   - name: Start {{ service }}
     service:
       name: "{{ service }}"
       state: "{{ state }}"
     register: service

   - debug:
       var: service
