- hosts: servers
  become: true
  user: {{ user }}
  gather_facts: false

  tasks:

   - name: Start tomcat
     service:
       name: "{{ service }}"
       state: "{{ state }}"
     register: tomcat

   - debug:
       var: tomcat
